spring:
  application:
      name: ventas

####### POSTGRESQL Configuration #########
  jpa:
    hibernate:
      ## To avoid conflicts, the automatic schema creation is turned off
      ddl-auto: none
  datasource:
    ## Database is not embedded. Spring Boot 2 - external database
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://pi.intranet.cat:5432/aplicaciondeventas
    username: aplicacionventas
    password: projectAplicacionVentas

server:
    port: 8443
    servlet:
        context-path: /ventas
    name: https://xrodrig.dnsnet.info:${server.port}
    ssl:
        enabled: true
        keyPassword: 123456
        #keyStore: file:/etc/cas/keystore
        keyStore: file:C:\Users\amgri\desenvolupament\ss-tfg-unir\xrodrigdnskeystore
        keyStorePassword: 123456

