spring:
  application:
      name: ventas

#https://zetcode.com/springboot/postgresql/
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://192.168.1.48:5432/aplicaciondeventas
    username: aplicacionventas
    password: projectAplicacionVentas

server:
    port: 8443
    servlet:
        context-path: /ventas
    name: https://xrodrig.dnsnet.info:${server.port}
    ssl:
        enabled: true
        keyPassword: 123456
        #keyStore: file:/etc/cas/keystore
        keyStore: file:C:\Users\amgri\desenvolupament\ss-tfg-unir\xrodrigdnskeystore
        keyStorePassword: 123456

